name: Daily Web Scraper Search Index

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to click a button to run it manually anytime

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Scraper Script
        run: node scraper.js

      - name: Commit and Push Updated Index to GitHub Pages
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add search-index.json
          git commit -m "Automated update of search index database" || exit 0
          git push